CREATE TABLE YOLOSWAG201/AUTHOR (
AUTHOR_ID  CHAR      (8)  PRIMARY KEY,  
AUTHOR_FNAME CHAR      (64)    NOT NULL,
AUTHOR_LNAME CHAR      (64)    NOT NULL,
DOB     DATE    NOT NULL,
MILSOLD CHAR      (64)    NOT NULL,
)

CREATE TABLE YOLOSWAG201/SHIPPING (
SHIPPINGOP     CHAR      (8)       PRIMARY KEY,  
COST           DEC      (255)     NOT NULL,
GUARANTEE      CHAR      (255)     NOT NULL,
)

CREATE TABLE YOLOSWAG201/INVOICE (
INVOICE_NO      CHAR  (8)  PRIMARY KEY,  
INVOICE_DATE    DATE       NOT NULL,
)

CREATE TABLE YOLOSWAG201/PUBLISHER (
PUBLISHER_NO            CHAR  (8)     PRIMARY KEY,  
PUBLISHER_OWNER_NO      CHAR  (64)    NOT NULL,
PUBLISHER_NAME          CHAR  (64)      NOT NULL,
CONSTRAINT PUBLISHER_OWNER_FK FOREIGN KEY (PUBLISHER_OWNER_NO)
REFERENCES PUBLISHER_OWNER(PUBLISHER_OWNER_NO),
)

CREATE TABLE YOLOSWAG201/PUBLISHER_OWNER (
OWNER_NO      CHAR  (8)     PRIMARY KEY,  
OWNER_NAME    CHAR  (64)    NOT NULL,
)

CREATE TABLE YOLOSWAG201/BOOKFORMAT (
FORMATID      CHAR  (8)     PRIMARY KEY,  
FORMATNAME    CHAR  (64)    NOT NULL,
)

CREATE TABLE YOLOSWAG201/PRIZE (
PRIZE_NO      CHAR  (8)     PRIMARY KEY,  
PRIZE_NAME    CHAR  (64)    NOT NULL,
PRIZE_AMOUNT  DEC   (255)   NOT NULL,
)

CREATE TABLE YOLOSWAG201/PRIZE_BOOK (
PRIZE_NO    CHAR  (8)     PRIMARY KEY,  
ISBN        CHAR  (16)    PRIMARY KEY,
CONSTRAINT PRIZE_NO_FK FOREIGN KEY (PRIZE_NO)
REFERENCES PRIZE(PRIZE_NO),
CONSTRAINT ISBN_FK FOREIGN KEY (ISBN)
REFERENCES ISBN(ISBN),
)

CREATE TABLE YOLOSWAG201/INVOICE (
INVOICE_NO      CHAR  (8)  PRIMARY KEY,
INVOICE_DATE    DATE       NOT NULL,
CUSTOMER_NO     CHAR  (8)  NOT NULL,
CONSTRAINT CUSTOMER_NO_FK FOREIGN KEY (CUSTOMER_NO)
REFERENCES CUSTOMER(CUSTOMER_NO),
)

CREATE TABLE YOLOSWAG201/CUSTOMER (
CUSTOMER_NO     CHAR      (8)  PRIMARY KEY,  
CUSTOMER_LNAME  CHAR      (64)    NOT NULL,
CUSTOMER_LNAME  CHAR      (64)    NOT NULL,
STREETNO        NUMERIC   (4)    NOT NULL,
STREET_NAME     CHAR      (64)    NOT NULL,
CITY            CHAR      (32)     NOT NULL,
PROVINCE        CHAR      (32)    NOT NULL,
POSTAL_CODE     CHAR      (16)    NOT NULL,
)

CREATE TABLE YOLOSWAG201/BOOK_WAREHOUSE (
WAREHOUSE_ID    CHAR  (8)     PRIMARY KEY,  
ISBN        CHAR  (16)    PRIMARY KEY,
CONSTRAINT WAREHOUSE_ID_FK FOREIGN KEY (WAREHOUSE_ID)
REFERENCES WAREHOUSE(WAREHOUSE_ID),
CONSTRAINT ISBN_FK FOREIGN KEY (ISBN)
REFERENCES ISBN(ISBN),
)

CREATE TABLE YOLOSWAG201/BOOK_INVOICE ( 
ISBN                    CHAR      (16)    PRIMARY KEY,
INVOICE_NO              CHAR      (8)     PRIMARY KEY,
SHIPPINGOP              CHAR      (8)     NOT NULL,
QTY                     NUMERIC   (4)     NOT NULL,
INVOICE_UNIT_PRICE      DEC       (255)   NOT NULL,
CONSTRAINT ISBN_FK FOREIGN KEY (ISBN)
REFERENCES ISBN(ISBN),
CONSTRAINT INVOICE_NO_FK FOREIGN KEY (INVOICE_NO)
REFERENCES INVOICE(INVOICE_NO),
CONSTRAINT SHIPPINGOP_FK FOREIGN KEY (SHIPPINGOP)
REFERENCES SHIPPING(SHIPPINGOP)
)